# Grafana Prometheus datasource configuration
# 
# @author Roberto de Souza <rabbittrix@hotmail.com>
# @license Apache-2.0

apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

