[package]
name = "gateway-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "gateway-service"
path = "src/main.rs"

[dependencies]
fx-gateway = { path = "../../crates/fx-gateway" }
fx-utils = { path = "../../crates/fx-utils" }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
prometheus = { workspace = true }
prometheus_exporter = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
