[package]
name = "fx-oms"
version = "0.1.3"
edition = "2021"
authors = ["Roberto de Souza <rabbittrix@hotmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/rabbittrix/Ultra-Low-Latency-FX-eTrading-Platform.git"
description = "Order management domain crate for FX eTrading workflows."

[dependencies]
fx-utils = { path = "../fx-utils" }
serde = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
