[package]
name = "fx-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fx-utils = { path = "../fx-utils" }
crossbeam = { workspace = true }
crossbeam-queue = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "matching_bench"
harness = false
